databases:
  - name: test_app_DB
    databaseName: test_app_db_v1pw
    user: test_app_db_v1pw_user
    region: singapore

services:
  - type: web
    name: test_app
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_app_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false